name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: mv demo_index.html index.html
    - run: git add .
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        PERSONAL_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        # 生成文件的目录
        PUBLISH_DIR: ./
